apiVersion: v1
clusters:
- cluster:
    server: https://D837C3FE6736ED69B3DEADB9ABA1610C.gr7.eu-west-3.eks.amazonaws.com
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1ETXdOekUxTWpjeE0xb1hEVE16TURNd05ERTFNamN4TTFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS3VoCkRzVFFUTzJaU3ZNNExDMC9Ea3FLcDBxejJlNVVyR0d4N3RHaTQwenlRRTJpWUNoWGt4dkhmYmFlUTdPM09Yd1gKR201Q2l3bk1zWEZPRFY3WWpsK1REWit3NklEYVZQaGJqak1KUHdCaWZ2a2lMd3BQd0c5TXdCU2s0MkxOOHJ1cwpGUndTZWRzNmpOQ0dSZ0ZzZERWejFQM2ZhK2IwMTJBZCtXbmdBQWZGbXRXYjFpM3NQbnR2Zi9zVEttSjlpTWFWCkkxV2pZdW1xNU43aGZWV2o2NGtOVXV5Q1hleTVLYllPM2lXcmlGeS9nQ0xSaFhtcWtPUXVvMk1ZMitSWkQ1QnEKdW8rR2ZWc2tiQ01ZNzVJMncwaVpBVWQvTGZBbWFDdUlCeUN6bjI3RkZ6RW4vY3pJQ3k0QS9xeVUrb3Y0Q0ZvMAp1ejUrL1hnZWM1VTk1d1pyYWdVQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZFNVRWZmd2b3lJd3VOYVdZRFBaOHZZKzNFS0pNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBRFJZRkZ2bGZjVzlDME1RK1BXagp4aVB0M0VVSmlENktuOE5xU3IxOFdXZVJ6V2YxT1lSenk3Z1poQW1aVm83V3RHN2w2cUczY3NWRVBGaGhwa2h4CkdIQ0xZVmFTUGJYWkdtNTJrbitoQnlNcnNWWTZWeWJINHJKamRuN0NTVmx1ZXZFQ0xVVVRnYnNKY1BpV1ErNEIKcE1zeVZIVmpaSnQ5dEZTTC90QzMvalI2d05pVzUwZHhoWDJVak1qdDY5TUZnMlNPRHJhUVV5R1AwaHhxajltMApZRmZaQVFNKy92RHRvbUZMMERnQUdYelYzUlRhck8wVC9GZDZoSUpBdlhFVU5hRFdqS3pMUDlNay8vNnhKQUdJCk9EeDFiSE1Ob0VZY3Z3RDFzRlZPSmVpVE1RMldmL0cvWGgzNHkxOHVHSVpxaUtja2FreTJZaUNTb2pHTXBGZkYKNm5vPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  name: aws_z809f9644
contexts:
- context:
    cluster: aws_z809f9644
    user: aws_z809f9644
  name: aws_z809f9644
current-context: aws_z809f9644
kind: Config
preferences: {}
users:
- name: aws_z809f9644
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1
      interactiveMode: IfAvailable
      command: qovery
      args:
      - cluster
      - get-token
      - --cluster-id
      - 809f9644-b3e4-400b-97fc-e2173d46a00e
